--------------------------------------------------------
--  File created - Tuesday-April-04-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COOKS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."COOKS" 
   (	"EMPNUM" NUMBER(*,0), 
	"COOKPOSITION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CUSTOMER" 
   (	"CUSTOMERID" NUMBER(*,0), 
	"FNAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"MINITIAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"LNAME" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"R_NUM" NUMBER(*,0), 
	"ORDERID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table DAILY_SALES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."DAILY_SALES" 
   (	"REST_NUM" NUMBER(*,0), 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SALEDATE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"DAILY_TOTAL" FLOAT(126)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table INVENTORY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."INVENTORY" 
   (	"NAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"COUNT_DETROIT" NUMBER(*,0), 
	"COUNT_DEARBORN" NUMBER(*,0), 
	"COUNT_ANNARBOR" NUMBER(*,0), 
	"ITEMID" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table LOCATIONS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LOCATIONS" 
   (	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"R_PHONE" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"RESTAURANTNUM" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table MANAGER
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MANAGER" 
   (	"EMPNUM" NUMBER(*,0), 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "ADMIN"."MENU" 
   (	"ITEMID#" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"VEGAN" VARCHAR2(3 BYTE) COLLATE "USING_NLS_COMP", 
	"PRICE" NUMBER(*,0), 
	"INVEN_STATUS" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ORDERS" 
   (	"ORDERID" NUMBER(*,0), 
	"ORDERDATE" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CUSTOMERID" NUMBER(*,0), 
	"STATUS" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"TOTAL" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table PHONE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PHONE" 
   (	"EMPNUM" NUMBER(*,0), 
	"PHONENUM" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ADMIN"."RESERVATION" 
   (	"RESERVATION_NUM" NUMBER(*,0), 
	"PARTYSIZE" NUMBER(*,0), 
	"TIME" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"RESERVE_DATE" VARCHAR2(15 BYTE) COLLATE "USING_NLS_COMP", 
	"REST_TABLE" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table REST_TABLES
--------------------------------------------------------

  CREATE TABLE "ADMIN"."REST_TABLES" 
   (	"NUM" NUMBER(*,0), 
	"AVAILABILITY" VARCHAR2(40 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table STAFF
--------------------------------------------------------

  CREATE TABLE "ADMIN"."STAFF" 
   (	"FNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"MINITIAL" VARCHAR2(1 BYTE) COLLATE "USING_NLS_COMP", 
	"LNAME" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"SSN" NUMBER(*,0), 
	"EMPNUM" NUMBER(*,0), 
	"SALARY" FLOAT(126), 
	"BIRTHDAY" DATE, 
	"POSITION" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"DATEOFEMPLOYEMENT" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Table WAITERS
--------------------------------------------------------

  CREATE TABLE "ADMIN"."WAITERS" 
   (	"EMPNUM" NUMBER(*,0), 
	"LOCATION" VARCHAR2(50 BYTE) COLLATE "USING_NLS_COMP", 
	"TABLENUM" NUMBER(*,0)
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table LOCATIONS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LOCATIONS" ADD PRIMARY KEY ("RESTAURANTNUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MANAGER" ADD PRIMARY KEY ("EMPNUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ADMIN"."RESERVATION" MODIFY ("RESERVATION_NUM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."RESERVATION" ADD PRIMARY KEY ("RESERVATION_NUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CUSTOMER" ADD PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DAILY_SALES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."DAILY_SALES" MODIFY ("REST_NUM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."DAILY_SALES" ADD PRIMARY KEY ("REST_NUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STAFF
--------------------------------------------------------

  ALTER TABLE "ADMIN"."STAFF" ADD PRIMARY KEY ("EMPNUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ORDERS" MODIFY ("ORDERID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ORDERS" ADD PRIMARY KEY ("ORDERID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WAITERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."WAITERS" ADD PRIMARY KEY ("EMPNUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INVENTORY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."INVENTORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVENTORY" MODIFY ("ITEMID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."INVENTORY" ADD PRIMARY KEY ("ITEMID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PHONE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PHONE" ADD PRIMARY KEY ("EMPNUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COOKS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COOKS" ADD PRIMARY KEY ("EMPNUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MENU" MODIFY ("ITEMID#" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."MENU" ADD PRIMARY KEY ("ITEMID#")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REST_TABLES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."REST_TABLES" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."REST_TABLES" ADD PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COOKS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."COOKS" ADD FOREIGN KEY ("EMPNUM")
	  REFERENCES "ADMIN"."STAFF" ("EMPNUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DAILY_SALES
--------------------------------------------------------

  ALTER TABLE "ADMIN"."DAILY_SALES" ADD FOREIGN KEY ("REST_NUM")
	  REFERENCES "ADMIN"."LOCATIONS" ("RESTAURANTNUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MANAGER
--------------------------------------------------------

  ALTER TABLE "ADMIN"."MANAGER" ADD FOREIGN KEY ("EMPNUM")
	  REFERENCES "ADMIN"."STAFF" ("EMPNUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHONE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PHONE" ADD FOREIGN KEY ("EMPNUM")
	  REFERENCES "ADMIN"."STAFF" ("EMPNUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table WAITERS
--------------------------------------------------------

  ALTER TABLE "ADMIN"."WAITERS" ADD FOREIGN KEY ("EMPNUM")
	  REFERENCES "ADMIN"."STAFF" ("EMPNUM") ENABLE;
